export type BodyRegion = {
  id: string;
  label: string;
  gender: "female" | "male" | "both";
  view: "front" | "back" | "head";
  bodyArea:
    | "kopf"
    | "gesicht"
    | "brust"
    | "bauch"
    | "arme"
    | "beine"
    | "intimbereich"
    | "ruecken";
  cx: number;
  cy: number;
  rx: number;
  ry: number;
};

// All coordinates are in percent (0–100) relative to SVG viewBox 0 0 100 200
// head view uses viewBox 0 0 100 120

export const FEMALE_REGIONS: BodyRegion[] = [
  // ── Gesicht & Kopf ──────────────────────────────────────────────────────────
  {
    id: "nasenkorrektur",
    label: "Nasenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 52,
    rx: 7,
    ry: 5,
  },
  {
    id: "lidkorrektur",
    label: "Lidkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 44,
    rx: 14,
    ry: 4,
  },
  {
    id: "facelift",
    label: "Facelift",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 55,
    rx: 20,
    ry: 14,
  },
  {
    id: "stirnlifting",
    label: "Stirnlifting",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 34,
    rx: 18,
    ry: 6,
  },
  {
    id: "wangenkorrektur",
    label: "Wangenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 58,
    rx: 22,
    ry: 8,
  },
  {
    id: "kinnkorrektur",
    label: "Kinnkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 68,
    rx: 10,
    ry: 5,
  },
  {
    id: "lippenkorrektur",
    label: "Lippenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 63,
    rx: 10,
    ry: 4,
  },
  {
    id: "ohrenkorrektur",
    label: "Ohrenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "kopf",
    cx: 50,
    cy: 50,
    rx: 28,
    ry: 6,
  },
  {
    id: "botox",
    label: "Botox / Anti-Aging",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 40,
    rx: 16,
    ry: 10,
  },
  {
    id: "hyaluron",
    label: "Hyaluron-Filler",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 62,
    rx: 14,
    ry: 6,
  },
  {
    id: "haartransplantation",
    label: "Haartransplantation",
    gender: "both",
    view: "head",
    bodyArea: "kopf",
    cx: 50,
    cy: 22,
    rx: 22,
    ry: 10,
  },

  // ── Brust (front) ───────────────────────────────────────────────────────────
  {
    id: "brust-vergroesserung",
    label: "Brustvergrößerung",
    gender: "female",
    view: "front",
    bodyArea: "brust",
    cx: 50,
    cy: 34,
    rx: 18,
    ry: 9,
  },
  {
    id: "brustverkleinerung",
    label: "Brustverkleinerung",
    gender: "female",
    view: "front",
    bodyArea: "brust",
    cx: 50,
    cy: 36,
    rx: 18,
    ry: 9,
  },
  {
    id: "bruststraffung",
    label: "Bruststraffung",
    gender: "female",
    view: "front",
    bodyArea: "brust",
    cx: 50,
    cy: 38,
    rx: 16,
    ry: 8,
  },

  // ── Bauch (front) ───────────────────────────────────────────────────────────
  {
    id: "bauchdeckenstraffung",
    label: "Bauchdeckenstraffung",
    gender: "both",
    view: "front",
    bodyArea: "bauch",
    cx: 50,
    cy: 53,
    rx: 16,
    ry: 8,
  },
  {
    id: "liposuktion",
    label: "Liposuktion",
    gender: "both",
    view: "front",
    bodyArea: "bauch",
    cx: 50,
    cy: 56,
    rx: 20,
    ry: 9,
  },
  {
    id: "mini-tummy-tuck",
    label: "Mini-Bauchdeckenstraffung",
    gender: "both",
    view: "front",
    bodyArea: "bauch",
    cx: 50,
    cy: 60,
    rx: 14,
    ry: 6,
  },

  // ── Arme (front) ────────────────────────────────────────────────────────────
  {
    id: "armstraffung",
    label: "Armstraffung",
    gender: "both",
    view: "front",
    bodyArea: "arme",
    cx: 50,
    cy: 46,
    rx: 32,
    ry: 5,
  },
  {
    id: "lipo-arme",
    label: "Liposuktion Arme",
    gender: "both",
    view: "front",
    bodyArea: "arme",
    cx: 50,
    cy: 48,
    rx: 30,
    ry: 4,
  },

  // ── Beine (front) ───────────────────────────────────────────────────────────
  {
    id: "oberschenkelstraffung",
    label: "Oberschenkelstraffung",
    gender: "both",
    view: "front",
    bodyArea: "beine",
    cx: 50,
    cy: 72,
    rx: 20,
    ry: 10,
  },
  {
    id: "lipo-beine",
    label: "Liposuktion Beine",
    gender: "both",
    view: "front",
    bodyArea: "beine",
    cx: 50,
    cy: 76,
    rx: 18,
    ry: 8,
  },
  {
    id: "wadenkorrektur",
    label: "Wadenkorrektur",
    gender: "both",
    view: "front",
    bodyArea: "beine",
    cx: 50,
    cy: 86,
    rx: 14,
    ry: 7,
  },

  // ── Intimbereich (front) ─────────────────────────────────────────────────────
  {
    id: "intimchirurgie",
    label: "Intimchirurgie",
    gender: "female",
    view: "front",
    bodyArea: "intimbereich",
    cx: 50,
    cy: 65,
    rx: 10,
    ry: 5,
  },
];

export const MALE_REGIONS: BodyRegion[] = [
  // ── Gesicht & Kopf ──────────────────────────────────────────────────────────
  {
    id: "nasenkorrektur",
    label: "Nasenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 52,
    rx: 7,
    ry: 5,
  },
  {
    id: "lidkorrektur",
    label: "Lidkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 44,
    rx: 14,
    ry: 4,
  },
  {
    id: "facelift",
    label: "Facelift",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 55,
    rx: 20,
    ry: 14,
  },
  {
    id: "stirnlifting",
    label: "Stirnlifting",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 34,
    rx: 18,
    ry: 6,
  },
  {
    id: "wangenkorrektur",
    label: "Wangenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 58,
    rx: 22,
    ry: 8,
  },
  {
    id: "kinnkorrektur",
    label: "Kinnkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 68,
    rx: 10,
    ry: 5,
  },
  {
    id: "lippenkorrektur",
    label: "Lippenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 63,
    rx: 10,
    ry: 4,
  },
  {
    id: "ohrenkorrektur",
    label: "Ohrenkorrektur",
    gender: "both",
    view: "head",
    bodyArea: "kopf",
    cx: 50,
    cy: 50,
    rx: 28,
    ry: 6,
  },
  {
    id: "botox",
    label: "Botox / Anti-Aging",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 40,
    rx: 16,
    ry: 10,
  },
  {
    id: "hyaluron",
    label: "Hyaluron-Filler",
    gender: "both",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 62,
    rx: 14,
    ry: 6,
  },
  {
    id: "haartransplantation",
    label: "Haartransplantation",
    gender: "both",
    view: "head",
    bodyArea: "kopf",
    cx: 50,
    cy: 22,
    rx: 22,
    ry: 10,
  },
  {
    id: "bartkorrektur",
    label: "Bartkorrektur / Barthaartransplantation",
    gender: "male",
    view: "head",
    bodyArea: "gesicht",
    cx: 50,
    cy: 66,
    rx: 16,
    ry: 7,
  },

  // ── Brust / Oberkörper (front) ───────────────────────────────────────────────
  {
    id: "gynaekomastie",
    label: "Gynäkomastie (Brustverkleinerung Mann)",
    gender: "male",
    view: "front",
    bodyArea: "brust",
    cx: 50,
    cy: 34,
    rx: 18,
    ry: 9,
  },
  {
    id: "pectoralis-implantate",
    label: "Pectoralis-Implantate",
    gender: "male",
    view: "front",
    bodyArea: "brust",
    cx: 50,
    cy: 37,
    rx: 16,
    ry: 7,
  },

  // ── Bauch (front) ───────────────────────────────────────────────────────────
  {
    id: "bauchdeckenstraffung",
    label: "Bauchdeckenstraffung",
    gender: "both",
    view: "front",
    bodyArea: "bauch",
    cx: 50,
    cy: 53,
    rx: 16,
    ry: 8,
  },
  {
    id: "liposuktion",
    label: "Liposuktion",
    gender: "both",
    view: "front",
    bodyArea: "bauch",
    cx: 50,
    cy: 56,
    rx: 20,
    ry: 9,
  },
  {
    id: "sixpack",
    label: "Sixpack-Sculpting (Hi-Def Lipo)",
    gender: "male",
    view: "front",
    bodyArea: "bauch",
    cx: 50,
    cy: 50,
    rx: 12,
    ry: 10,
  },

  // ── Arme (front) ────────────────────────────────────────────────────────────
  {
    id: "armstraffung",
    label: "Armstraffung",
    gender: "both",
    view: "front",
    bodyArea: "arme",
    cx: 50,
    cy: 46,
    rx: 32,
    ry: 5,
  },

  // ── Beine (front) ───────────────────────────────────────────────────────────
  {
    id: "oberschenkelstraffung",
    label: "Oberschenkelstraffung",
    gender: "both",
    view: "front",
    bodyArea: "beine",
    cx: 50,
    cy: 72,
    rx: 20,
    ry: 10,
  },
  {
    id: "wadenkorrektur",
    label: "Wadenkorrektur",
    gender: "both",
    view: "front",
    bodyArea: "beine",
    cx: 50,
    cy: 86,
    rx: 14,
    ry: 7,
  },
  {
    id: "unterschenkel-implantate",
    label: "Unterschenkel-Implantate",
    gender: "male",
    view: "front",
    bodyArea: "beine",
    cx: 50,
    cy: 88,
    rx: 12,
    ry: 6,
  },

  // ── Rücken (back) ────────────────────────────────────────────────────────────
  {
    id: "po-lifting",
    label: "Po-Lifting",
    gender: "both",
    view: "back",
    bodyArea: "ruecken",
    cx: 50,
    cy: 60,
    rx: 18,
    ry: 12,
  },
  {
    id: "rueckenstraffung",
    label: "Rückenstraffung",
    gender: "both",
    view: "back",
    bodyArea: "ruecken",
    cx: 50,
    cy: 42,
    rx: 16,
    ry: 10,
  },
  {
    id: "lipo-ruecken",
    label: "Liposuktion Rücken",
    gender: "both",
    view: "back",
    bodyArea: "ruecken",
    cx: 50,
    cy: 48,
    rx: 18,
    ry: 8,
  },
];

// Combined export for convenience
const MALE_IDS = new Set(MALE_REGIONS.map((r) => r.id));
export const ALL_REGIONS: BodyRegion[] = [
  ...FEMALE_REGIONS.filter((r) => !MALE_IDS.has(r.id)),
  ...MALE_REGIONS,
];
